default_platform(:ios)

platform :ios do
  before_all do |lane|
  	  cocoapods
  end

  desc "Upload Shield & Metadata to App Store"
  lane :prod do
      upload_as("Text Protector", "com.ericlewis.spam-shield")
  end

  desc "Upload Shield Pro & Metadata to App Store"
  lane :prod_pro do
      upload_as("Text Protector Pro", "com.ericlewis.spam-shieldpro")
  end
  
  desc "Upload Shield to TestFlight"
  lane :beta do
      upload_tf("Text Protector")
  end

  desc "Upload Shield Pro to TestFlight"
  lane :beta_pro do
      upload_tf("Text Protector Pro")
  end

  desc "Run Shield Unit & UI Tests"
  lane :tests do
      run_tests(scheme: "Text Protector")
  end

  desc "Run Shield Pro Unit & UI Tests"
  lane :tests_pro do
      run_tests(scheme: "Text Protector Pro")
  end

  def upload_as(scheme, appId)
	  capture_screenshots(scheme: scheme)
  	  common_pre_upload(scheme)
      upload_to_app_store(app_identifier: appId, username: "ericlewis777+apple@gmail.com")
      common_post_upload
  end

  def upload_tf(scheme)
  	  common_pre_upload(scheme)
      upload_to_testflight(username: "ericlewis777+apple@gmail.com", skip_waiting_for_build_processing: true)
      common_post_upload
  end	

  def common_pre_upload(scheme)
  	  sync_code_signing(type: "appstore")
      build_app(scheme: scheme)
  end

  def common_post_upload()
  	  clean_build_artifacts
      commit_version_bump
      push_to_git_remote
  end
end
